-- 给 items 表添加缺失的字段
ALTER TABLE items ADD COLUMN IF NOT EXISTS tags JSONB DEFAULT '[]'::jsonb;
ALTER TABLE items ADD COLUMN IF NOT EXISTS tool_link JSONB DEFAULT NULL;
ALTER TABLE items ADD COLUMN IF NOT EXISTS description TEXT DEFAULT '';
ALTER TABLE items ADD COLUMN IF NOT EXISTS props TEXT DEFAULT '';
